module ProfessionList
  LIST = [
    "Allergist/Immunologist",
    "Anesthesiologist",
    "Cardiac Electrophysiologist",
    "Cardiologist",
    "Colon and Rectal Surgeon",
    "Critical Care Medicine Specialist",
    "Dermatologist",
    "Emergency Medicine Physician",
    "Endocrinologist",
    "Family Medicine Physician",
    "Gastroenterologist",
    "Geriatric Medicine Specialist",
    "Hematologist",
    "Hematologist-Oncologist",
    "Hospitalist",
    "Infectious Disease Specialist",
    "Intensivist",
    "Internist",
    "Interventional Cardiologist",
    "Medical Geneticist",
    "Neonatologist",
    "Nephrologist",
    "Neurologist",
    "Neurosurgeon",
    "Nuclear Medicine Specialist",
    "Obstetrician",
    "Gynecologist",
    "Ophthalmologist",
    "Orthopedic Surgeon",
    "Otolaryngologist (ENT)",
    "Pain Management Specialist",
    "Pathologist",
    "Pediatrician",
    "Pediatric Cardiologist",
    "Pediatric Endocrinologist",
    "Pediatric Gastroenterologist",
    "Pediatric Hematologist-Oncologist",
    "Pediatric Infectious Disease Specialist",
    "Pediatric Nephrologist",
    "Pediatric Neurologist",
    "Pediatric Pulmonologist",
    "Pediatric Rheumatologist",
    "Physiatrist (Physical Medicine and Rehabilitation)",
    "Plastic Surgeon",
    "Psychiatrist",
    "Psychologist",
    "Pulmonologist",
    "Radiation Oncologist",
    "Radiologist",
    "Reproductive Endocrinologist",
    "Rheumatologist",
    "Sleep Medicine Specialist",
    "Spinal Surgeon",
    "Sports Medicine Physician",
    "Surgeon (General)",
    "Thoracic Surgeon",
    "Transplant Surgeon",
    "Trauma Surgeon",
    "Urologist",
    "Vascular Surgeon"
  ]
end

